services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=
      - DB_NAME=go_ticket
      - JWT_SECRET=kiVq9ai2aSuuKCb/B71kpe6G/oWtBOHr8I3WFO4fpwo=
      - PORT=8080
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=go_ticket
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
